### ISSUE TITLE
Upload directory

### ISSUE THREAD

**Issue by SIMULATAN** [codecov/test-results-action#72]
Java's JUnit creates one XML file per test class. Hence, a multitude of files has to be uploaded to codecov.
Unfortunately, this action doesn't seem to support that.

## What I've tried
- `directory: build/test-results`
- `file: 'build/test-results/**'`
- `files: 'build/test-results/**'`

## Example runs
- [with glob](https://github.com/SnotyMe/snoty-backend/actions/runs/9323958688/job/25668224236) ([workflow](https://github.com/SnotyMe/snoty-backend/actions/runs/9323958688/workflow))
- [with `directory`](https://github.com/SnotyMe/snoty-backend/actions/runs/9323919044) ([workflow](https://github.com/SnotyMe/snoty-backend/actions/runs/9323919044/workflow))  

## CLI problem?
This doesn't seem to be action-specific but rather a limitation of the CLI. I'm still opening this issue here as the glob matching could be done JS-side and the files passed through `--file` flags.

**Comment by webknjaz** [comment]
This would be useful in the context of the coverage upload action too, by the way.

**Comment by mprins** [comment]
Keeping a list of files as part of the workflow is not really a viable option as tests come and go.

It does not seem to be that hard to modify this section: https://github.com/codecov/test-results-action/blob/7c17a47169c9bcb333ee4b2ea4db40cf682b92bf/src/buildExec.ts#L105-L109

to create a list of files that match the glob. eg. https://github.com/isaacs/node-glob or https://github.com/sindresorhus/globby or... (NodeJS still only has experimental glob support!)

**Comment by webknjaz** [comment]
I thought that the coverage action is already able to do globs. I'd recommend reusing the same code instead of maintaining two slightly different duplicates. It calls for a shared library for that reusable code.

**Comment by mprins** [comment]
I've added a `files` option with a glob in https://github.com/Tailormap/tailormap-api/pull/951/commits/d6cd84aedae122d6a10ec9c761eba55c1e1f094e

It give a warning about files not found, but to my surprise it uploads the files:

```
==> Uploader SHASUM verified (eb902009cb800fdefbce291c1357953f80e29382f43c7a98cce3b57d2b4d8cec  codecov)
==> Running version v0.7.4
==> Running command '/home/runner/work/_actions/codecov/test-results-action/v1/dist/codecov do-upload'
/home/runner/work/_actions/codecov/test-results-action/v1/dist/codecov do-upload -f target/failsafe-reports/TEST-*.xml -C d6cd84aedae122d6a10ec9c761eba55c1e1f094e --report-type test_results
info - 2024-09-16 12:[28](https://github.com/Tailormap/tailormap-api/actions/runs/10883608137/job/30197252447?pr=951#step:10:29):18,444 -- ci service found: github-actions
warning - 2024-09-16 12:28:18,486 -- Some files were not found --- {"not_found_files": ["target/failsafe-reports/TEST-*.xml"]}
info - 2024-09-16 12:28:18,510 -- Found 28 test_results files to report
info - 2024-09-16 12:28:18,510 -- > /home/runner/work/tailormap-api/tailormap-api/target/failsafe-reports/TEST-org.tailormap.api.ValidateGeoToolsInArtifactIntegrationTest.xml
info - 2024-09-16 12:28:18,510 -- > /home/runner/work/tailormap-api/tailormap-api/target/failsafe-reports/TEST-org.tailormap.api.controller.LayerExportControllerIntegrationTest.xml
info - 2024-09-16 12:28:18,510 -- > /home/runner/work/tailormap-api/tailormap-api/target/failsafe-reports/TEST-org.tailormap.api.controller.UserControllerIntegrationTest.xml
info - 2024-09-16 12:28:18,510 -- > /home/runner/work/tailormap-api/tailormap-api/target/failsafe-reports/TEST-org.tailormap.api.controller.FeaturesControllerIntegrationTest.xml
```

see https://app.codecov.io/gh/Tailormap/tailormap-api/tests/HTM-1215_codecov

**Comment by joseph-sentry** [comment]
globs and wildcards should work, maybe try: `**/build/test-results/**` as the argument to `files`?

for more clarity on those arguments 
`directory`: this is the root directory where the CLI will start walking, since this is a singular directory no globs / wildcards allowed
`folders_to_ignore`: list of names of folders to not bother walking through, this is also an exact match, no globs or wildcards allowed
`files`: list of paths to explicitly upload, these are matched relative to the directory

**Comment by SIMULATAN** [comment]
@joseph-sentry thank you for the suggestion and explanations!

I just tried using your proposed value, and some files are indeed detected, but not all of them (see [job log](https://github.com/SnotyMe/snoty-backend/actions/runs/11641517852/job/32420121275?pr=47#step:8:37))
Removing the `/` of `**/build` - which was present in my workaround glob pattern and worked there ([job log](https://github.com/SnotyMe/snoty-backend/actions/runs/11641339509/job/32419737698#step:8:33)) - fixes it. Furthermore, I also added back the trailing `/TEST-*.xml` to avoid uploading these weird `.bin` and `.bin.idx` files.

My final value of `files: '**build/test-results/**/TEST-*.xml'` therefore works just as intended, thank you! Closing this one as the cases shared here *should* be covered.

**Comment by ssbarnea** [comment]
Considering that I did a search via https://sourcegraph.com/search?q=path:.github/workflows+codecov/test-results-action%40v1+%22directory:+./%22+&patternType=keyword&sm=0 and I found zero cases of use of wildcard, maybe we need to do something to document it and ensure it works.

One of the most obvious examples would be for .tox users a `directory: .tox/**/junit.xml`. I hope it would work.
